### ISSUE TITLE
getByDisplayValue is missing in TypeScript types

### ISSUE THREAD

**Issue by theforce1989** [testing-library/cypress-testing-library#42]
- `cypress-testing-library` version: 3.0.1
- `node` version: 11.10.0
- `yarn` version: 1.14.0

Relevant code or config

```javascript
cy.getByDisplayValue("something");
```

**What you did:**
updated to  `cypress-testing-library` 3.0.1 and because of breaking changes in `dom-testing-library` as outlined in the release notes, I switched my `getByValue` queries to `getByDisplayValue`.

**What happened:**
TS compile fails because `getByDisplayValue` is not defined in `cypress-testing-library/typings`

**Suggested solution:**
update typings to reflect the changes in the API

**Comment by kentcdodds** [comment]
Thanks for the issue. Could you make a pull request to add them?

**Comment by ppi-buck** [comment]
The PR should also include updated tests inside https://github.com/testing-library/cypress-testing-library/blob/master/cypress/integration/commands.spec.js and https://github.com/testing-library/cypress-testing-library/blob/master/tests/typescript-types/test.spec.ts if possible. 

Because these tests are missing the *ByValue or *ByDisplayValue all together the issue didn't occur automatically earlier.
